Feature/tweaks before release
vexl-it/vexl pull request #45
Opened 2023-05-01 12:41 UTC by kaladivo

2023-05-02 10:07 UTC, kaladivo commented
- [ ] is buying is selling is wrong
 - [ ] Approved message should not appear
 - [ ] Check message setting - messages dissapearing
 - [ ] When removing or blocking user navigate to chat list
 - [ ] When areYouSure block dialog is dissmised, do not show allert error
 - [ ] Ellipse chat header on small screen

2023-05-02 11:27 UTC, SamTremko requested changes

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/AccepDeclineButtons.tsx
> +            Alert.alert('Error. TODO') // TODO error handling
Handle, remove TODO

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/ChatInfoModal.tsx
> +          <Stack mt="$7"></Stack>
Change to height

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/ChatRequestPreview.tsx
> +        {/* todo what if removed? */}
delete

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/ChatRequestPreview.tsx
> +        <Text fos={20} color="$black" fontFamily="$body500">
Change color in case of message deleted

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/ChatRequestPreview.tsx
> +          <Text fontFamily={'$body600'} mb="$2" fos={14} col={'#808080'}>
use from theme

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/ChatRequestPreview.tsx
> +          {/* TODO no offer */}
display that offer was deleted

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ChatDetailScreen/components/MessagesListOrApprovalPreview.tsx
> +  // TODO handle no messages
pls remove, add text

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/ContactListSelect/components/SearchBar.tsx
> +          text={t(allSelected ? 'common.selectAll' : 'common.deselectAll')}
check translation

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/InsideRouter/components/MarketplaceScreen/components/OffersList.tsx
> +  ListComponent,
ListHeaderComponent

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/InsideRouter/components/MessagesScreen/components/LastMessagePreview.tsx
> +  const baseProps = {
Move this outside of component, use styled from tamagui

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/OfferDetailScreen/indexOld.tsx
> +import {type RootStackScreenProps} from '../../navigationTypes'
Delete this file

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/SetContactsScreen/index.tsx
> +// type Props = RootStackScreenProps<'SetContacts'>
remove

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/Input.tsx
> +  multiline?: boolean
Pick from props

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/components/OfferWithBubbleTip.tsx
> +          </Text>
reuse component from chat with same logic

2023-05-02 11:27 UTC, SamTremko commented on apps/mobile/src/utils/atomUtils/notNullableAtom.ts
> +import {atom, type Atom, type SetStateAction, type WritableAtom} from 'jotai'
pls remove this file

2023-05-02 11:27 UTC, SamTremko commented on packages/cryptography/package.json
> +    "rimraf": "^4.4.0",
add to dev deps

2023-05-02 11:27 UTC, SamTremko commented on packages/domain/src/general/messaging.ts
> +  uuid: ChatMessageId, // TODo change
remove todo

2023-05-02 11:27 UTC, SamTremko commented on eas.json
> +{
pls remove

2023-05-03 08:21 UTC, SamTremko approved these changes

2023-05-03 08:22 UTC, merged