Add phone number bug in chat
vexl-it/vexl pull request #782
Opened 2024-01-31 21:29 UTC by SamTremko

2024-01-31 21:29 UTC, SamTremko commented
Current dependencies on/for this PR:
* `main`
  * **PR #782** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/782?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vexl-it/vexl/782?utm_source=stack-comment).

2024-02-01 09:36 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/QuickActionBanner.tsx
> +              normalizedNumber: fullPhoneNumber,
Good catch, no need to parse the number again

2024-02-01 09:54 UTC, kaladivo requested changes

2024-02-01 09:54 UTC, kaladivo commented on apps/mobile/src/state/chat/atoms/revealContactActionAtom.ts
> +          )
Can we do this inside the condition below?

2024-02-01 09:54 UTC, kaladivo commented on apps/mobile/src/state/chat/utils/addRealLifeInfoToChat.ts
> +    }
What if identityRevealData and contactRevealData are both nonnull? Only identityRevealData will be processed in that case

2024-02-01 09:54 UTC, kaladivo commented on packages/domain/src/general/DeanonymizedUser.ts
> +  fullPhoneNumber: E164PhoneNumber.optional(),
👍

2024-02-01 09:54 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/QuickActionBanner.tsx
> +          'APPROVE_REVEAL')) &&
We want to show this only if the last message is response on reveal? Is that desired? If I approve contact reveal and I send text  message right after that, will the other side see the banner? Should it?

2024-02-01 13:34 UTC, SamTremko commented on apps/mobile/src/state/chat/utils/addRealLifeInfoToChat.ts
> +    }
yes that is true, but this should not happen, as we are using this function in per message processing

2024-02-01 13:36 UTC, kaladivo commented on apps/mobile/src/state/chat/utils/addRealLifeInfoToChat.ts
> +    }
Can we split it into two? Otherwise I guaratee you, in the future, one of us will call it, thinking it does both.

2024-02-01 13:39 UTC, kaladivo approved these changes

2024-02-01 13:40 UTC, kaladivo requested changes
Jus one more comment

2024-02-01 14:25 UTC, kaladivo approved these changes

2024-02-01 14:30 UTC, merged