Change order of messages in tradechecklist
vexl-it/vexl pull request #783
Opened 2024-01-31 22:01 UTC by SamTremko

2024-01-31 22:02 UTC, SamTremko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/783?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #782** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/782?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #783** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/783?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vexl-it/vexl/783?utm_source=stack-comment).

2024-02-01 10:01 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/utils/buildMessagesListData.ts
> +    ...result.slice(-2),
What if result.length === 2? Will Vexl bot message be placed correctly?

2024-02-01 10:01 UTC, kaladivo requested changes

2024-02-01 10:01 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/utils/buildMessagesListData.ts
> +    ...result.slice(-2),
What if result.length === 2? Will Vexl bot message be placed correctly?

2024-02-01 13:29 UTC, kaladivo approved these changes

2024-02-01 14:39 UTC, kaladivo approved these changes

2024-02-01 14:48 UTC, closed without merging