Possibility to add trade event to OS calendar
vexl-it/vexl pull request #830
Opened 2024-02-26 15:30 UTC by SamTremko

2024-02-26 15:30 UTC, SamTremko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/830?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#830** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/830?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#829** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/829?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#828** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/828?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vexl-it/vexl/830?utm_source=stack-comment).

2024-02-27 10:10 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/atoms/addEventToCalendarAndTryToResolveThePermissionsAlongTheWay.ts
> +        console.log('Here are all your calendars:')
Unnecessary log

2024-02-27 10:11 UTC, kaladivo reviewed
Make sure to add calendar explanation to infoplist to prevent fail in prod https://docs.expo.dev/versions/latest/sdk/calendar/

2024-03-06 20:08 UTC, kaladivo requested changes

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/VexlbotMessageItem/components/TradeChecklistMeetingLocationView.tsx
> +              })
It might make sense to make an action atom for this

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +  event: Omit<Partial<Event>, 'id'>
Does it make sense to use `Partial<Event>` here?

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/VexlbotMessageItem/components/TradeChecklistMeetingLocationView.tsx
> +              })
Whan happens if the event is deleted? Should we at least display some kind of error message to user?

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +  ): Promise<CalendarEventId | undefined> => {
If possible return `Task` please

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +      event: Omit<Partial<Event>, 'id'>
Why partial?

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +        (e) => {
call `reportError`?

2024-03-06 20:08 UTC, kaladivo commented on packages/domain/src/general/messaging.ts
> +  tradeChecklistCalendarEventId: CalendarEventId.optional(),
Wouldn't it make more sense to put this into `TradeChecklistInState` in `apps/mobile/src/state/tradeChecklist/domain.ts`

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/VexlbotMessageItem/components/TradeChecklistDateAndTimeView.tsx
> +            })
This all can be put into action atom that is created inside of chatMolecule. It would reduce number of hook calls need in this component.

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/state/useLogout.ts
> +      await failSilently(Calendar.deleteCalendarAsync(vexlCalendarId))
Do we really want to do this on delete?

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +        (e) => {
permission missing error alert should be displayed

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +              reportError('error', new Error('Error creating calendar event'), {
What about all the other reasons. If they are not displayed to users is it ok to omit reporting them?

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/VexlbotMessageItem/components/TradeChecklistDateAndTimeView.tsx
> +            void addEventToCalendar({
What if we already know the event location here (it's sent after they agreed on location). Why not add it, if it is set

2024-03-06 20:08 UTC, kaladivo commented on apps/mobile/src/components/ChatDetailScreen/components/VexlbotMessageItem/components/TradeChecklistMeetingLocationView.tsx
> +        {!!calendarEventId && (
What if user firstly agree on location and later they agree on date&time. Will they have to scroll up and click this again?

2024-03-07 07:55 UTC, SamTremko commented on apps/mobile/src/state/useLogout.ts
> +      await failSilently(Calendar.deleteCalendarAsync(vexlCalendarId))
It seemed to me, that if user deletes Vexl app, it should also delete all the stuff connected to it, so also events in calendar, but I can remove that

2024-03-07 07:56 UTC, SamTremko commented on apps/mobile/src/utils/calendar.ts
> +  event: Omit<Partial<Event>, 'id'>
This is actually the type of `event` that this call requires: 

`await Calendar.createEventAsync(calendarId, event)`

So therefore this type.

2024-03-07 07:59 UTC, SamTremko commented on apps/mobile/src/utils/calendar.ts
> +      event: Omit<Partial<Event>, 'id'>
The same case as above, this type is required by `expo-calendar`

2024-03-07 07:59 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +  event: Omit<Partial<Event>, 'id'>
So if you pass `{}` it's a valid argument?

2024-03-07 08:04 UTC, SamTremko commented on apps/mobile/src/utils/calendar.ts
> +  event: Omit<Partial<Event>, 'id'>
I know its strange, but according to the interface it is:

`export async function createEventAsync(
  calendarId: string,
  eventData: Omit<Partial<Event>, 'id'> = {}
): Promise<string>`

2024-03-07 08:04 UTC, kaladivo commented on apps/mobile/src/state/useLogout.ts
> +      await failSilently(Calendar.deleteCalendarAsync(vexlCalendarId))
I would leave calendar deletion up to the user aka, don't think it is a good idea to delete it by default. If anything, Vexl should ask.

2024-03-07 08:06 UTC, SamTremko commented on apps/mobile/src/state/useLogout.ts
> +      await failSilently(Calendar.deleteCalendarAsync(vexlCalendarId))
OK, I will change that

2024-03-07 08:09 UTC, kaladivo commented on apps/mobile/src/utils/calendar.ts
> +  event: Omit<Partial<Event>, 'id'>
that's not what I am arguing about.

Do we ever want to create an empty event? If not let's create custom interface to specify what we want the event to have. I think at least event name & date should be mandatory.

2024-03-07 11:07 UTC, kaladivo approved these changes

2024-03-08 09:49 UTC, merged