App startup bugs
vexl-it/vexl pull request #859
Opened 2024-03-06 13:40 UTC by SamTremko

2024-03-06 13:40 UTC, SamTremko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/859?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#859** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/859?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#830** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/830?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#829** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/829?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#828** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/828?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @SamTremko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-06 20:12 UTC, kaladivo commented on apps/mobile/src/AnimatedSplashScreen.tsx
> +    <Stack f={1}>
Position='relative' should be added here right?

2024-03-06 20:13 UTC, kaladivo requested changes
Let's talk about this tmrw

2024-03-06 20:13 UTC, kaladivo commented on apps/mobile/src/AnimatedSplashScreen.tsx
> +    <Stack f={1}>
Position='relative' should be added here right?

2024-03-06 20:13 UTC, kaladivo commented on apps/mobile/src/App.tsx
> +        <App />
Will this really prevent rendering the whole app until splashScreen is finished?

2024-03-07 11:04 UTC, kaladivo approved these changes

2024-03-08 10:20 UTC, merged

2024-03-08 10:20 UTC, SamTremko commented
### Merge activity

* **Mar 8, 5:20 AM EST**: @SamTremko merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vexl-it/vexl/859).