Add listing type and new categories elements to offer form
vexl-it/vexl pull request #905
Opened 2024-03-14 09:50 UTC by SamTremko

2024-03-14 09:51 UTC, SamTremko commented
* **#905** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/905?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @SamTremko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-20 12:12 UTC, kaladivo commented on packages/resources-utils/src/offers/utils/encryptOfferPublicPayload.ts
> +  listingType: z.string(),
Map to locaitonState

2024-03-20 12:13 UTC, kaladivo commented on packages/domain/src/general/offers.ts
> +  deliveryMethod: z.array(DeliveryMethod).default([]),
Use location state with fallback for older versions (in resource-utils)

2024-03-20 13:16 UTC, kaladivo requested changes

2024-03-20 13:16 UTC, kaladivo commented on packages/resources-utils/src/offers/utils/encryptOfferPublicPayload.ts
> +  deliveryMethod: z.array(z.string()).optional(),
Use location state with fallback for older versions (in resource-utils)

2024-03-20 13:16 UTC, kaladivo commented on packages/domain/src/general/offers.ts
> +  deliveryMethod: z.array(DeliveryMethod).default([]),
Use location state with fallback for older versions (in resource-utils)

2024-03-20 13:16 UTC, kaladivo commented on packages/domain/src/general/offers.ts
> +  singlePrice: z.number().optional(),
use amountBottomLimit/amountTopLimit

2024-03-20 13:16 UTC, kaladivo commented on packages/domain/src/general/offers.ts
> +  locationState: LocationState.default('IN_PERSON'),
No default, always set when creating offer

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/CurrentBtcPrice.tsx
> +  btcPriceWithStateAtom: Atom<BtcPriceDataWithState | undefined>
Make this atom accept only currency code and interact with currentBtcPriceAtom directly

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/InsideRouter/components/BitcoinPriceChart.tsx
> +      void refreshBtcPrice(selectedCurrencyAtom)()
Make sure that the price is refreshed when selected currency changes

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
> +      } as OfferPublicPart)
```suggestion
      } satisfies OfferPublicPart)
```

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
> +      } as OfferPublicPart)
```suggestion
      } satisfies OfferPublicPart)
```

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
> +      } as OfferPublicPart)
```suggestion
      } satisfies OfferPublicPart)
```

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
> +      !checkConditionsToCreateOfferAreMet({offerForm: get(offerFormAtom), t})
Rename to `checkConditionsToCreateOfferAreMetAlertIfNot`

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
> +  const toggleCurrencyActionAtom = atom(
setCurrencyActionAtom

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/useBtcOfferContent.tsx
> +            key={t('offerForm.premiumOrDiscount.premiumOrDiscount')}
Should the key be there?

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/useBtcOfferContent.tsx
> +            key={t('offerForm.expiration.expiration')}
Should the key be there?

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/useProductOfferContent.tsx
> +            key={t('offerForm.price')}
Check keys in this file also

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/OfferForm/components/ListingType/useContent.tsx
> +        type: 'BITCOIN' as ListingType,
use `as const`

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/components/OfferForm/index.tsx
>          item.customSection ? (
`<Fragment key={...}>`

<script>alert('ajaj');</script>

2024-03-20 13:16 UTC, kaladivo commented on apps/mobile/src/state/marketplace/atoms/offersToSeeInMarketplace.ts
> +      one.publicPart.listingType !== 'OTHER' &&
Make sure other offer has always locationState set

2024-03-20 13:41 UTC, SamTremko commented on apps/mobile/src/utils/bigNumberToString.ts
> +    return `${Math.round(number / 1_000)}M`
check this conversion

2024-03-20 17:55 UTC, SamTremko commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
>    const nullableOfferTypeAtom = atom<OfferType | undefined>(undefined)
change offer type for product to oposite compared to BTC offer

2024-03-25 13:22 UTC, kaladivo commented on apps/mobile/src/components/OfferForm/components/LocationsList.tsx
> +          key={loc.latitude}
loc has Id. Use id as a key

2024-03-25 13:23 UTC, kaladivo commented on apps/mobile/src/components/OfferForm/components/LocationsList.tsx
> +          key={loc.latitude}
```suggestion
  key={loc.placeId}
```

2024-03-25 13:23 UTC, kaladivo commented on apps/mobile/src/components/OfferForm/components/LocationsList.tsx
> +          key={loc.latitude}
```suggestion
  key={loc.placeId}
```

2024-03-25 13:35 UTC, kaladivo approved these changes

2024-03-25 13:35 UTC, kaladivo commented on packages/resources-utils/src/offers/utils/encryptOfferPublicPayload.ts
Remove v2 where it does not make sense

2024-03-25 14:08 UTC, merged

2024-03-25 14:08 UTC, SamTremko commented
### Merge activity

* **Mar 25, 10:08 AM EDT**: @SamTremko merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vexl-it/vexl/905).