Remove singlePriceState from OfferForm
vexl-it/vexl pull request #975
Opened 2024-04-12 10:14 UTC by SamTremko

2024-04-12 10:14 UTC, SamTremko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/975?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#975** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/975?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#938** <a href="https://app.graphite.dev/github/pr/vexl-it/vexl/938?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @SamTremko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-15 12:06 UTC, kaladivo requested changes

2024-04-15 12:06 UTC, kaladivo commented on apps/mobile/src/state/useSetAppLanguageFromStore.ts
> +  console.log(`Preferences app language: ${preferences.appLanguage}`)
Remove unnecessary log

2024-04-15 12:06 UTC, kaladivo commented on apps/mobile/src/components/ModifyOffer/atoms/offerFormStateAtoms.ts
> +  const _singlePriceActiveAtom = atom<boolean>(true)
Let's remove `_` in the naming, since this atom is used outside of toggleSinglePriceActiveAtom.

2024-04-15 12:06 UTC, kaladivo commented on apps/mobile/src/components/DebugScreen/components/LanguagePicker.tsx
> -          const newI18n = new I18n(translations)
Are you sure? Current app language is just the preferences atom it won't modify I18n settings

2024-04-15 12:20 UTC, SamTremko commented on apps/mobile/src/components/DebugScreen/components/LanguagePicker.tsx
> -          const newI18n = new I18n(translations)
We have the hook `useSetAppLanguageFromStore()` which is part of the `LoggedInHookGroup` which should then handle the change of `i18n`

2024-04-15 12:41 UTC, kaladivo approved these changes

2024-04-15 13:01 UTC, merged

2024-04-15 13:01 UTC, SamTremko commented
### Merge activity

* **Apr 15, 9:01 AM EDT**: @SamTremko merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vexl-it/vexl/975).